parameters: {}
environment: {}
packages:
  - name: sample
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: hello
        binary: false
        main: "hello.php"
        runtime: php:default
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
